# Generated by Django 4.2.15 on 2024-08-06 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Meals', 'Meals'), ('Training', 'Training'), ('Wifi', 'Wifi'), ('Office Supplies', 'Office Supplies'), ('Maintenance', 'Maintenance'), ('Software', 'Software'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
