# Generated by Django 4.1.13 on 2024-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_substitute_approversubstitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('approver', 'Approver'), ('staff', 'Staff'), ('substitute', 'Substitute')], max_length=20),
        ),
    ]
